import { defineConfig } from '@apify/oxlint-config';

export default defineConfig({
    ignorePatterns: [
        '**/node_modules',
        '**/dist',
        '**/coverage',
        '**/.turbo',
        '**/website/build',
        '**/website/.docusaurus',
        '**/*.d.ts',
        'packages/templates/templates/**',
        'packages/templates/scripts/**',
        'test/e2e/**',
    ],
    globals: {
        vi: 'readonly',
        vitest: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        expectTypeOf: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
    },
    rules: {
        'no-undef': 'off',
        'no-console': 'off',
        'no-throw-literal': 'error',
        eqeqeq: ['error', 'smart'],
        yoda: 'error',

        'typescript/consistent-type-imports': ['error', { disallowTypeAnnotations: false }],
        'typescript/consistent-type-definitions': ['error', 'interface'],
        'typescript/no-explicit-any': 'off',
        'typescript/ban-ts-comment': 'off',
        'typescript/no-unused-vars': 'off',
        'typescript/no-empty-function': 'off',
        'typescript/no-empty-object-type': 'off',
        'typescript/no-empty-interface': 'off',
        'typescript/no-useless-constructor': 'off',
        'typescript/no-namespace': ['error', { allowDeclarations: true }],
        'typescript/no-this-alias': 'error',
        'typescript/no-var-requires': 'error',
        'typescript/no-require-imports': 'off',
        'typescript/consistent-type-assertions': 'error',
        'typescript/no-unnecessary-qualifier': 'error',
        'typescript/no-inferrable-types': 'off',
        'typescript/no-unsafe-declaration-merging': 'off',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/related-getter-setter-pairs': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/no-deprecated': 'warn',
        'typescript/prefer-find': 'error',
        'typescript/prefer-string-starts-ends-with': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/consistent-type-exports': 'error',
        'typescript/prefer-optional-chain': 'error',
        'typescript/prefer-regexp-exec': 'error',
        'typescript/no-misused-promises': ['error', { checksVoidReturn: { arguments: false } }],
        'typescript/no-unnecessary-template-expression': 'error',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-array-delete': 'error',
        'typescript/return-await': 'off',
        'typescript/use-unknown-in-catch-callback-variable': 'off',
        'typescript/no-unnecessary-condition': 'off',
        'typescript/no-confusing-void-expression': 'off',
        'typescript/switch-exhaustiveness-check': 'off',
        'typescript/no-unnecessary-type-assertion': 'off',
        'typescript/no-unsafe-enum-comparison': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/promise-function-async': 'off',
        'typescript/require-await': 'off',
        'typescript/strict-void-return': 'off',
        'typescript/prefer-readonly-parameter-types': 'off',
        'typescript/no-use-before-define': 'off',

        'import/no-duplicates': 'error',
        'import/no-default-export': 'off',

        'unicorn/no-empty-file': 'off',

        // Rules pulled in by `@apify/oxlint-config` that the codebase does not
        // currently satisfy. Disabled here to keep this migration scoped to a
        // config refactor; flip them back on in follow-up cleanup PRs.
        'prefer-destructuring': 'off',
        'no-unassigned-vars': 'off',
        'jest/expect-expect': 'off',
        'jest/valid-title': 'off',
        'promise/valid-params': 'off',
    },
    overrides: [
        {
            files: ['test/**/*', 'packages/*/test/**/*'],
            rules: {
                'typescript/consistent-type-imports': 'off',
                'typescript/no-floating-promises': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/await-thenable': 'off',
                'typescript/no-deprecated': 'off',
                'typescript/no-array-delete': 'off',
                'typescript/no-mixed-enums': 'off',
                'typescript/no-implied-eval': 'off',
                'no-console': 'off',
                'no-control-regex': 'off',
                'no-empty': 'off',
                'import/no-duplicates': 'off',
                'jest/no-conditional-expect': 'off',
                'jest/no-disabled-tests': 'off',
                'vitest/no-conditional-tests': 'off',
                'vitest/hoisted-apis-on-top': 'off',
            },
        },
        {
            files: ['packages/templates/**/*'],
            rules: {
                'typescript/no-unused-vars': 'off',
                'no-unused-vars': 'off',
            },
        },
    ],
});
