import { randomUUID } from 'node:crypto';

import type { Redis } from 'ioredis';

import type * as storage from '@crawlee/types';

// ─── Key-name helpers ─────────────────────────────────────────────────────────
const REGISTRY_KEY = 'rq:registry';
const registryDataKey = (id: string) => `rq:registry:data:${id}`;

// ─── Lua script ───────────────────────────────────────────────────────────────

/**
 * Atomically get-or-create a queue entry in the registry.
 *
 * Uses `HSETNX` so only the first concurrent caller wins the candidateId. All
 * callers then read back the authoritative id and receive the same queue info.
 *
 * KEYS[1] = registry hash (`rq:registry`)
 * ARGV[1] = queue name
 * ARGV[2] = candidateId (UUID generated by the caller)
 * ARGV[3] = ISO timestamp for createdAt / modifiedAt / accessedAt
 *
 * Returns the winning queue id (string).
 */
const LUA_GET_OR_CREATE = `
local registryKey = KEYS[1]
local name        = ARGV[1]
local candidateId = ARGV[2]
local nowISO      = ARGV[3]

local created = redis.call('HSETNX', registryKey, name, candidateId)
local id      = redis.call('HGET',   registryKey, name)

if created == 1 then
  local dataKey = 'rq:registry:data:' .. id
  redis.call('HSET', dataKey,
    'id',                  id,
    'name',                name,
    'createdAt',           nowISO,
    'modifiedAt',          nowISO,
    'accessedAt',          nowISO,
    'totalRequestCount',   '0',
    'handledRequestCount', '0')

  local metaKey = 'rq:' .. id .. ':meta'
  redis.call('HSET', metaKey,
    'id',                  id,
    'name',                name,
    'createdAt',           nowISO,
    'modifiedAt',          nowISO,
    'accessedAt',          nowISO,
    'totalRequestCount',   '0',
    'handledRequestCount', '0')
else
  -- Queue already existed – just bump accessedAt
  local dataKey = 'rq:registry:data:' .. id
  redis.call('HSET', dataKey, 'accessedAt', nowISO)
end

return id
`;

// ─── Client ───────────────────────────────────────────────────────────────────

/**
 * A {@linkcode storage.RequestQueueCollectionClient} backed by Redis.
 *
 * The registry of all named queues lives in a single hash at key
 * `rq:registry` (name → id). Full metadata for each queue is stored in a
 * separate hash at `rq:registry:data:{id}`.
 */
export class RedisRequestQueueCollectionClient implements storage.RequestQueueCollectionClient {
    private readonly redis: Redis;

    constructor(redis: Redis) {
        this.redis = redis;
    }

    async list(): Promise<storage.PaginatedList<storage.RequestQueueInfo>> {
        const registry = await this.redis.hgetall(REGISTRY_KEY);
        const items: storage.RequestQueueInfo[] = [];

        for (const id of Object.values(registry ?? {})) {
            const data = await this.redis.hgetall(registryDataKey(id));
            if (!data?.id) continue;

            const total = parseInt(data.totalRequestCount ?? '0', 10);
            const handled = parseInt(data.handledRequestCount ?? '0', 10);
            items.push({
                id: data.id,
                name: data.name || undefined,
                createdAt: new Date(data.createdAt ?? Date.now()),
                modifiedAt: new Date(data.modifiedAt ?? Date.now()),
                accessedAt: new Date(data.accessedAt ?? Date.now()),
                totalRequestCount: total,
                handledRequestCount: handled,
                pendingRequestCount: total - handled,
            });
        }

        return {
            total: items.length,
            count: items.length,
            offset: 0,
            limit: items.length,
            items,
        };
    }

    async getOrCreate(name: string): Promise<storage.RequestQueueInfo> {
        const candidateId = randomUUID();
        const now = new Date().toISOString();

        const winningId = (await (this.redis as Redis).eval(
            LUA_GET_OR_CREATE,
            1,
            REGISTRY_KEY,
            name,
            candidateId,
            now,
        )) as string;

        const data = await this.redis.hgetall(registryDataKey(winningId));
        const total = parseInt(data?.totalRequestCount ?? '0', 10);
        const handled = parseInt(data?.handledRequestCount ?? '0', 10);

        return {
            id: winningId,
            name: data?.name ?? name,
            createdAt: new Date(data?.createdAt ?? now),
            modifiedAt: new Date(data?.modifiedAt ?? now),
            accessedAt: new Date(data?.accessedAt ?? now),
            totalRequestCount: total,
            handledRequestCount: handled,
            pendingRequestCount: total - handled,
        };
    }
}
