name: Bug report
description: Report incorrect or unexpected behavior of a module
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        If you have a question, please ask it on [GitHub Discussions](https://github.com/apify/crawlee/discussions) or in our [Discord server](https://discord.gg/jyEM2PRvMU)

  - type: dropdown
    id: package
    attributes:
      label: Which package is this bug report for? If unsure which one to select, leave blank
      multiple: false
      options:
        - "@crawlee/core"
        - "@crawlee/cheerio (CheerioCrawler)"
        - "@crawlee/jsdom (JSDOMCrawler)"
        - "@crawlee/playwright (PlaywrightCrawler)"
        - "@crawlee/puppeteer (PuppeteerCrawler)"
        - "@crawlee/basic (BasicCrawler)"
        - "@crawlee/http (HttpCrawler)"
        - "@crawlee/browser (BrowserCrawler)"
        - "@crawlee/utils"
        - "@crawlee/browser-pool"
        - "@crawlee/memory-storage"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with the code sample below:
        1. do thing
        2. call x method
        3. observe behavior
        4. see error logs below
    validations:
      required: true

  - type: textarea
    id: codesample
    attributes:
      label: Code sample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: TypeScript
      placeholder: |
        // Your code sample should be...
        // ... Minimal - use as little code as possible that still produces the same problem  (and is understandable)
        // ... Complete - Provide all parts someone else needs to reproduce your problem
        // ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem

  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Which version of the package are you using? Run `npm list <package>` in your project directory and paste the output.
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: |
        Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
        If you are using TypeScript, please include its version (`npm list typescript`) as well.
      placeholder: Node.js version 16+ is required for Crawlee
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?

  - type: checkboxes
    id: apify
    attributes:
      label: Apify platform
      description: Did you also encounter this issue when running your code on Apify's platform? (if unsure what that is, leave unticked)
      options:
        - label: Tick me if you encountered this issue on the Apify platform

  - type: input
    id: next-release
    attributes:
      label: I have tested this on the `next` release
      description: |
        This issue might already be fixed in a development release (tagged as `next` on npm). This is not required, but it helps us greatly.
        To install the latest development release run `npm i <package>@next` in your project directory.
        Run `npm list <package>` and provide the full version that is printed.
      placeholder: 3.0.5-beta.50

  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your bug report.
