import { playwrightUtils } from '@crawlee/playwright';
import { puppeteerUtils } from '@crawlee/puppeteer';
import { downloadListOfUrls, parseOpenGraph, sleep, social } from '@crawlee/utils';
export * from '@crawlee/core';
export * from '@crawlee/utils';
export * from '@crawlee/basic';
export * from '@crawlee/browser';
export * from '@crawlee/http';
export * from '@crawlee/jsdom';
export * from '@crawlee/linkedom';
export * from '@crawlee/cheerio';
export * from '@crawlee/puppeteer';
export * from '@crawlee/playwright';
export * from '@crawlee/browser-pool';
export * from '@crawlee/fs-storage';
export declare const utils: {
    puppeteer: typeof puppeteerUtils;
    playwright: typeof playwrightUtils;
    log: import("@apify/log").Log;
    social: typeof social;
    sleep: typeof sleep;
    downloadListOfUrls: typeof downloadListOfUrls;
    parseOpenGraph: typeof parseOpenGraph;
};
