import _ from 'underscore';
import util from 'util';
import { checkParamOrThrow } from 'apify-client/build/utils';
import { normalizeUrl } from 'apify-shared/utilities';

export const computeUniqueKey = (url, keepUrlFragment) => normalizeUrl(url, keepUrlFragment);

/**
 * Represents a URL to be crawled, optionally including HTTP method, headers, payload and other metadata.
 * The `Request` object also stores information about errors that occurred during processing of the request.
 *
 * Each `Request` instance has the `uniqueKey` property, which can be either specified
 * manually in the constructor or generated automatically from the URL. Two requests with the same `uniqueKey`
 * are considered as pointing to the same web resource. This behavior applies to all Apify SDK classes,
 * such as {@link RequestList}, {@link RequestQueue} or {@link PuppeteerCrawler}.
 *
 * Example use:
 *
 * ```javascript
 * const request = new Apify.Request({
 *     url: 'http://www.example.com',
 *     headers: { Accept: 'application/json' },
 * });
 *
 * ...
 *
 * request.userData.foo = 'bar';
 * request.pushErrorMessage(new Error('Request failed!'));
 *
 * ...
 *
 * const foo = request.userData.foo;
 * ```
 * @param {object} options All `Request` parameters are passed
 *   via an options object with the following keys:
 * @param {String} options.url URL of the web page to crawl. It must be a non-empty string.
 * @param {String} [options.uniqueKey] A unique key identifying the request.
 * Two requests with the same `uniqueKey` are considered as pointing to the same URL.
 *
 * If `uniqueKey` is not provided, then it is automatically generated by normalizing the URL.
 * For example, the URL of `HTTP://www.EXAMPLE.com/something/` will produce the `uniqueKey`
 * of `http://www.example.com/something`.
 *
 * The `keepUrlFragment` option determines whether URL hash fragment is included in the `uniqueKey` or not.
 * Beware that the HTTP method and payload are not included in the `uniqueKey`,
 * so requests to the same URL but with different HTTP methods or different POST payloads
 * are all considered equal and will be deduplicated by {@link RequestList} and {@link RequestQueue}.
 *
 * Pass an arbitrary non-empty text value to the `uniqueKey` property
 * to override the default behavior and specify which URLs shall be considered equal.
 * @param {String} [options.method='GET']
 * @param {String|Buffer} [options.payload]
 *   HTTP request payload, e.g. for POST requests.
 * @param {Object} [options.headers={}]
 *   HTTP headers in the following format:
 *   ```
 *   {
 *       Accept: 'text/html',
 *       'Content-Type': 'application/json'
 *   }
 *   ```
 * @param {Object} [options.userData={}]
 *   Custom user data assigned to the request. Use this to save any request related data to the
 *   request's scope, keeping them accessible on retries, failures etc.
 * @param {Boolean} [options.keepUrlFragment=false]
 *   If `false` then the hash part of a URL is removed when computing the `uniqueKey` property.
 *   For example, this causes the `http://www.example.com#foo` and `http://www.example.com#bar` URLs
 *   to have the same `uniqueKey` of `http://www.example.com` and thus the URLs are considered equal.
 *   Note that this option only has an effect if `uniqueKey` is not set.
 *
 * @property {String} id
 *   Request ID
 * @property {String} url
 *   URL of the web page to crawl.
 * @property {String} loadedUrl
 *   An actually loaded URL after redirects, if present. HTTP redirects are guaranteed
 *   to be included.
 *
 *   When using {@link PuppeteerCrawler}, meta tag and JavaScript redirects may,
 *   or may not be included, depending on their nature. This generally means that redirects,
 *   which happen immediately will most likely be included, but delayed redirects will not.
 * @property {String} uniqueKey
 *   A unique key identifying the request.
 *   Two requests with the same `uniqueKey` are considered as pointing to the same URL.
 * @property {String} method
 *   HTTP method, e.g. `GET` or `POST`.
 * @property {String} payload
 *   HTTP request payload, e.g. for POST requests.
 * @property {Boolean} retry
 *   Indicates whether the request will be automatically retried or not.
 * @property {Number} retryCount
 *   Indicates the number of times the crawling of the request has been retried on error.
 * @property {String[]} errorMessages
 *   An array of error messages from request processing.
 * @property {Object} headers
 *   Object with HTTP headers. Key is header name, value is the value.
 * @property {Object} userData
 *   Custom user data assigned to the request.
 * @property {Date} handledAt
 *   Indicates the time when the request has been processed.
 *   Is `null` if the request has not been crawled yet.
 */
class Request {
    constructor(options = {}) {
        checkParamOrThrow(options, 'options', 'Object');

        const {
            id,
            url,
            loadedUrl = null,
            uniqueKey,
            method = 'GET',
            payload = null,
            noRetry = false,
            retryCount = 0,
            errorMessages = null,
            headers = {},
            userData = {},
            keepUrlFragment = false,
            handledAt = null,
        } = options;


        checkParamOrThrow(id, 'id', 'Maybe String');
        checkParamOrThrow(url, 'url', 'String');
        checkParamOrThrow(loadedUrl, 'url', 'Maybe String');
        checkParamOrThrow(uniqueKey, 'uniqueKey', 'Maybe String');
        checkParamOrThrow(method, 'method', 'String');
        checkParamOrThrow(payload, 'payload', 'Maybe Buffer | String');
        checkParamOrThrow(noRetry, 'retry', 'Boolean');
        checkParamOrThrow(retryCount, 'retryCount', 'Number');
        checkParamOrThrow(errorMessages, 'errorMessages', 'Maybe Array');
        checkParamOrThrow(headers, 'headers', 'Object');
        checkParamOrThrow(userData, 'userData', 'Object');
        checkParamOrThrow(handledAt, 'handledAt', 'Maybe String | Date');

        if (method === 'GET' && payload) throw new Error('Request with GET method cannot have a payload.');

        if (!url) throw new Error('The "url" option cannot be empty string.');

        this.id = id;
        this.url = url;
        this.loadedUrl = loadedUrl;
        // NOTE: If URL is invalid, computeUniqueKey() returns null which was causing weird errors
        this.uniqueKey = uniqueKey || computeUniqueKey(url, keepUrlFragment) || url;
        this.method = method;
        this.payload = payload;
        this.noRetry = noRetry;
        this.retryCount = retryCount;
        this.errorMessages = errorMessages;
        this.headers = headers;
        this.userData = userData;

        // TODO: What is this text parsing good for? There's no unit test for it...
        // eslint-disable-next-line no-nested-ternary
        this.handledAt = _.isDate(handledAt)
            ? handledAt
            : (handledAt ? new Date(handledAt) : null);
    }

    /**
     * Stores information about an error that occurred during processing of this request.
     *
     * You should always use Error instances when throwing errors in JavaScript.
     *
     * Nevertheless, to improve the debugging experience when using third party libraries
     * that may not always throw an Error instance, the function performs a type
     * inspection of the passed argument and attempts to extract as much information
     * as possible, since just throwing a bad type error makes any debugging rather difficult.
     *
     * @param {Error|String} errorOrMessage Error object or error message to be stored in the request.
     * @param {Object} [options]
     * @param {Boolean} [options.omitStack=false] Only push the error message without stack trace when true.
     */
    pushErrorMessage(errorOrMessage, options = {}) {
        const { omitStack } = options;
        let message;
        const type = typeof errorOrMessage;
        if (type === 'object') {
            if (!errorOrMessage) {
                message = 'null';
            } else if (errorOrMessage instanceof Error) {
                message = omitStack
                    ? errorOrMessage.message
                    // .stack includes the message
                    : errorOrMessage.stack;
            } else if (errorOrMessage.message) {
                message = errorOrMessage.message; // eslint-disable-line prefer-destructuring
            } else if (errorOrMessage.toString() !== '[object Object]') {
                message = errorOrMessage.toString();
            } else {
                try {
                    message = util.inspect(errorOrMessage);
                } catch (err) {
                    message = 'Unable to extract any message from the received object.';
                }
            }
        } else if (type === 'undefined') {
            message = 'undefined';
        } else {
            message = errorOrMessage.toString();
        }

        if (!this.errorMessages) this.errorMessages = [];
        this.errorMessages.push(message);
    }

    /**
     * Flags the request with no retry which prevents {@link BasicCrawler}
     * (and {@PuppeteerCrawler} + {@CheerioCrawler}, since they use {@BasicCrawler} internally)
     * from retrying the request after an error occurs.
     *
     * Optionally accepts a message that will be used to construct
     * and throw an Error.
     *
     * @param {String} [message]
     */
    doNotRetry(message) {
        this.noRetry = true;
        if (message) throw new Error(message);
    }
}

export default Request;
