# This workflow runs for every PR or push to master, verifying the TS typings allow successful compilation.

name: Check TS support

on:
    pull_request:
    push:
        branches: [ master ]

jobs:
    check:
        name: Check TS support
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
                    registry-url: https://registry.npmjs.org/
            -   name: Check TS support
                run: |
                    npm install             # install SDK deps
                    yarn link               # link the local version of SDK
                    cd ts-check             # go to the TS skeleton project directory
                    yarn                    # install its deps
                    yarn link apify         # link local SDK version to the skeleton project
                    tsc -p tsconfig.json    # build the TS project
                    node dist/index.js      # run the built project
