name: Check PR title

on:
    pull_request_target:
        types: [ opened, edited, synchronize ]

jobs:
    check_pr_title:
        name: 'Check PR title'
        runs-on: ubuntu-22.04
        steps:
            -   uses: apify/actions/pr-title-check@v1.3.0
