name: Update new issue

on:
    issues:
        types:
            - opened

jobs:
    label_issues:
        name: Label issues
        runs-on: ubuntu-22.04
        permissions:
            issues: write

        steps:
            # Add the "t-tooling" label to all new issues
            -   uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
                with:
                    script: |
                        github.rest.issues.addLabels({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          labels: ["t-tooling"]
                        })
